apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::028067553394:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-B0ZHzqT2ai2h
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
      
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::028067553394:user/suresh
      username: suresh 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-21T23:00:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1144"
  uid: 0fc5875b-f15c-4d0a-9261-c7e85bd0b1d1
